### ISSUE TITLE
It doesn't work on 1.20.1, I know you didn't list it in the versions but I tried and it doesn't work 

### ISSUE THREAD

**Issue by sashaironfist** [dxxxxy/EssentialCosmeticsUnlocker#12]

**Comment by dxxxxy** [comment]
I only listed the major versions, however, 1.20.1 should work. A small number of users reported this issue, however, I could not replicate it myself. I'll try again later.

**Comment by dxxxxy** [comment]
It still works, perhaps you haven't done the steps correctly. There are some closed issues that you can look into.

![image](https://github.com/dxxxxy/EssentialCosmeticsUnlocker/assets/42523606/ce6fe782-38bd-4bd1-9e12-680a24f36e1f)

![image](https://github.com/dxxxxy/EssentialCosmeticsUnlocker/assets/42523606/51ae8705-fdaf-4adf-aa8a-a847ffbb1128)

**Comment by sashaironfist** [comment]
![image](https://github.com/dxxxxy/EssentialCosmeticsUnlocker/assets/97107514/5548c40c-05c2-4022-bfae-0b8174b2748e)
![image](https://github.com/dxxxxy/EssentialCosmeticsUnlocker/assets/97107514/07b29d31-3d33-41ec-84a7-fdc53b0d34e7)
![image](https://github.com/dxxxxy/EssentialCosmeticsUnlocker/assets/97107514/ec8e298d-641a-41d6-8e34-154c4ff56819)

**Comment by sashaironfist** [comment]
all on the same game launch

**Comment by dxxxxy** [comment]
> ![image](https://user-images.githubusercontent.com/97107514/277060954-5548c40c-05c2-4022-bfae-0b8174b2748e.png) ![image](https://user-images.githubusercontent.com/97107514/277061003-07b29d31-3d33-41ec-84a7-fdc53b0d34e7.png) ![image](https://user-images.githubusercontent.com/97107514/277061020-ec8e298d-641a-41d6-8e34-154c4ff56819.png)

You have the wrong essential jar in your mods folder. I suggest rereading the steps. The one there should be around 40mb.

**Comment by sashaironfist** [comment]
oh ok thanks  but I downloaded from the official website?

**Comment by sashaironfist** [comment]
I already fixed it thanks :)

**Comment by sashaironfist** [comment]
I fixed it thanks :)
