### ISSUE TITLE
Can you unlock the Aether paid skins?

### ISSUE THREAD

**Issue by Blasg2** [dxxxxy/EssentialCosmeticsUnlocker#18]
This is not a issue, just a feature request, if possible lol 
I don't know where to post this kind of stuff.... if there's a better place please teach me

**Comment by dxxxxy** [comment]
What is that?

**Comment by Blasg2** [comment]
If you have the Aether mod and open your inventory, there`ll be a button to unlock some paid skins for an aether creature

**Comment by dxxxxy** [comment]
It doesn't interest me, sorry.
