### ISSUE TITLE
trash

### ISSUE THREAD

**Issue by GHDavor** [dxxxxy/EssentialCosmeticsUnlocker#22]
bro this is total garbage, it doesn't unlock anything and if i use the legacy jar it just throws this:
![imagen_2024-02-12_210258758](https://github.com/dxxxxy/EssentialCosmeticsUnlocker/assets/91034453/be51a8ac-ca88-4ad5-a63c-de007deb53ae)

**Comment by GHDavor** [comment]
also, didn't mean to be so mean, but i had a rough day. sorry

**Comment by dxxxxy** [comment]
You're not reading the instructions...

**Comment by GHDavor** [comment]
> Owner

i did. i read and did everything the instructions said and still
