### ISSUE TITLE
works for only 1.8.9

### ISSUE THREAD

**Issue by CafeGT86** [dxxxxy/EssentialCosmeticsUnlocker#26]
Ok so OWNER pls lissen , i did EXACLY everything u sayd on 1.20.4 : 1.20.2 : 1.20.1 : 1.20 etc and i found out it works only for 1.8.9 
PLS fix it i did intall the good essential from modrith and put the legacy one  in mods , dont try to say i didnt do anything good bcs i did everything , the mod dosent work for new versions , only 1.8.9!!!

**Comment by dxxxxy** [comment]
You didn't read the instructions correctly.

**Comment by CafeGT86** [comment]
Na NAAA i did EVERYTHING EXACALY LIKE 1.8.9  EXACLY BUT ON 1.8.9 WORKED and on 1.20.4 DIDNT
