### ISSUE TITLE
1.20.4 compatibility

### ISSUE THREAD

**Issue by OCTAMIUM** [dxxxxy/EssentialCosmeticsUnlocker#30]
does it work for 1.20.4  if not please can you ? :D

**Comment by skythebro** [comment]
I just tried it on 1.20.4 and as you can see it does work.
![image_2024-03-16_184318409](https://github.com/dxxxxy/EssentialCosmeticsUnlocker/assets/96251661/ac3a3789-b7f0-4e98-bce4-09a0e12e099c)

**Comment by L1nuxe** [comment]
> I just tried it on 1.20.4 and as you can see it does work. ![image_2024-03-16_184318409](https://private-user-images.githubusercontent.com/96251661/313421468-ac3a3789-b7f0-4e98-bce4-09a0e12e099c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMzI4OTIsIm5iZiI6MTcxMTAzMjU5MiwicGF0aCI6Ii85NjI1MTY2MS8zMTM0MjE0NjgtYWMzYTM3ODktYjdmMC00ZTk4LWJjZTQtMDlhMGUxMmUwOTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE0NDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NzdhNjk5NWQ5NGNjYmRlOGNiZGQwMmRmYjUxOGVkOGNkNmQ0Njg5MzlkMmVlZDZlMjczNjgzNzg4MmQyZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hXJ0AoygaV4Z2xvYs-mrsYmRvx22mdywngvIzn63NEo)

hey i have a question, how do you set this up with ATLauncher since im too broke to buy cosmetics

Thanks, L1nux

**Comment by 18209550** [comment]
just use prism launcher it's easier

> > I just tried it on 1.20.4 and as you can see it does work. ![image_2024-03-16_184318409](https://private-user-images.githubusercontent.com/96251661/313421468-ac3a3789-b7f0-4e98-bce4-09a0e12e099c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMzI4OTIsIm5iZiI6MTcxMTAzMjU5MiwicGF0aCI6Ii85NjI1MTY2MS8zMTM0MjE0NjgtYWMzYTM3ODktYjdmMC00ZTk4LWJjZTQtMDlhMGUxMmUwOTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE0NDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NzdhNjk5NWQ5NGNjYmRlOGNiZGQwMmRmYjUxOGVkOGNkNmQ0Njg5MzlkMmVlZDZlMjczNjgzNzg4MmQyZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hXJ0AoygaV4Z2xvYs-mrsYmRvx22mdywngvIzn63NEo)
> 
> hey i have a question, how do you set this up with ATLauncher since im too broke to buy cosmetics
> 
> Thanks, L1nux

**Comment by OCTAMIUM** [comment]
do i have to add ecu and the ecu legacy both? , i add the ecu , but it dosen't remove the prices ,

**Comment by OCTAMIUM** [comment]
can you give youre discord?

**Comment by 18209550** [comment]
Are you using fabric or forge?

**Comment by 18209550** [comment]
also my discord account is this:

Discord (https://discord.com/users/891802283661209600)
<https://discord.com/users/891802283661209600>

**Comment by OCTAMIUM** [comment]
fabric 1.20.4 with some optimization mods

**Comment by OCTAMIUM** [comment]
my discord is phueyyy add me please

**Comment by OCTAMIUM** [comment]
hey , i just had a suggestion , you see essential dosent show cosmetics on cracked servers , is there a way to bypass that , if u could do something about that, even if it's client side would be nice

**Comment by PalmaKokosich** [comment]
You know how to install this mod, then I haven't been able to figure out where to shove it for 30 minutes.
