### ISSUE TITLE
Trouble making the mod work with Fabric

### ISSUE THREAD

**Issue by TovMachin** [dxxxxy/EssentialCosmeticsUnlocker#32]
Hey,

I recently changed from a Forge modpack to a Fabric one.
The mod worked fine with forge but I have trouble getting it to work with fabric.

__Essential Mod :__ `essential_1-3-1-1_fabric_1-20-1.jar` *49.8MB*
__ECU :__ `ecu-1.3.0.jar`
__Fabric version :__ `0.15.9 for MC 1.20.1`

* *The modpack I play is a custom one made using CurseForge*

Is there anything I'm missing ?

*Edit: Tried downgrading to Essentials 1.3.0.3 (version released before Last Checked for 1.20.1) still doesn't work*

**Comment by OM3GA6400** [comment]
same

**Comment by dxxxxy** [comment]
My apologies for the super late reply, I was not able to replicate the issue using your exact parameters. Used the Fabric 1.20.1 installer downloaded from https://essential.gg/downloads to then relaunch with the installer replaced by the mod itself (50MB) taken from the .minecraft/essential folder.
