### ISSUE TITLE
Suggestion to change the data path

### ISSUE THREAD

**Issue by MacaylaMarvelous81** [dxxxxy/EssentialCosmeticsUnlocker#35]
Currently, the cosmetic data dump and config file are located at `$LOCALAPPDATA`. This corresponds to `<user>/AppData/Local` on Windows, but it could be undefined on other environments, such as on a Linux installation, which means the user will have to define `$LOCALAPPDATA` themselves.

I suggest using a subdirectory in the Minecraft game folder since game data, including mods, are usually placed there, users won't need to deal with any additional configuration, and it would keep profiles/instances separate if the user has multiple.

**Comment by dxxxxy** [comment]
APPDATA (roaming) will be used instead. It is impossible to use Minecraft's dir variable as it does not exist in later versions of the game and breaks universal compatibility (I encountered it just now).

**Comment by MacaylaMarvelous81** [comment]
`$APPDATA` also is just for Windows and unrelated to the Minecraft installation so I feel like it runs into the same problem. Here's what happens if I check `$APPDATA` on my Debian computer:

```sh
jomarm@Dell-Inspiron-7773:~$ echo $APPDATA

jomarm@Dell-Inspiron-7773:~$ 
```

**Comment by dxxxxy** [comment]
Other than setting it manually, I see no other option.
