### ISSUE TITLE
Game crashes on 1.20.1 as well

### ISSUE THREAD

**Issue by BubblyTainted** [dxxxxy/EssentialCosmeticsUnlocker#39]
there was an issue already posted for 1.20.6, and I wanted to add that it also crashes on 1.20.1

**Comment by lorke1** [comment]
Pretty sure the mod is 1.8.9 only...

**Comment by BubblyTainted** [comment]
> Pretty sure the mod is 1.8.9 only...

I was hoping maybe the dev would update it, if they dont do you know of any other projects that do the same thing? I enjoy some of the cosmetics and only play singleplayer, paying for cosmetics in creative singleplayer seems an odd thing to do

**Comment by dxxxxy** [comment]
The mod is for all versions that you can run Essential on. If there are any issues, then please provide more details. Additionally, you can join my new discord server where I am more active (it's in the pinned issue).

**Comment by BubblyTainted** [comment]
> The mod is for all versions that you can run Essential on. If there are any issues, then please provide more details. Additionally, you can join my new discord server where I am more active (it's in the pinned issue).

I wanted to, but the discord invite gives me a ''whoops unable to join'' error, besides that, the game crashes without giving too much info, just ''game crashed'' and that's about it, I can provide the log if that would help? thank you for answering
