### ISSUE TITLE
Not understanding 

### ISSUE THREAD

**Issue by Beerandoo** [dxxxxy/EssentialCosmeticsUnlocker#4]
Could you leave a tutorial for how to install this on fabric? I really want to use this, it's an amazing mod you've made, I'm just quite confused on how to use it. Thankyou

**Comment by dxxxxy** [comment]
There is nothing to install, it's just a mod. Read the notes, there is something extra to do with Essential on Fabric.

**Comment by dxxxxy** [comment]
I think a tutorial on how to drag and drop files is not needed.

**Comment by Beerandoo** [comment]
> I think a tutorial on how to drag and drop files is not needed.

Atleast an explanation as to what to do with the jar file would be extremely helpful pls.

**Comment by dxxxxy** [comment]
The Essential.jar you place in your mods folder when you download it from their website is the installer. The installer downloads the actual mod into the .minecraft/essential folder which is loaded from there. Fabric loads this mod (ecu) before the actual Essential mod so you need to drag the actual Essential mod into your mods folder alongside ecu, which means that you have the 40mb+ Essential mod and ecu in your mods folder (without the installer). On Forge, this is not necessary. 

`-legacy.jar` is for Forge versions 1.8 to 1.12.

**Comment by Beerandoo** [comment]
> The Essential.jar you place in your mods folder when you download it from their website is the installer. The installer downloads the actual mod into the .minecraft/essential folder which is loaded from there. Fabric loads this mod (ecu) before the actual Essential mod so you need to drag the actual Essential mod into your mods folder alongside ecu, which means that you have the 40mb+ Essential mod and ecu in your mods folder (without the installer). On Forge, this is not necessary. 
> 
> `-legacy.jar` is for Forge versions 1.8 to 1.12.

Thankyou so much for this reply, I got it working. I really appreciate you taking the time to explain this to me. I apologize for the inconvenience and thankyou again for helping me out. You've created something amazing. Much love and take care

**Comment by dxxxxy** [comment]
No worries, enjoy ♥.
