### ISSUE TITLE
1.19.4 unblocking issue

### ISSUE THREAD

**Issue by wildcodemaster** [dxxxxy/EssentialCosmeticsUnlocker#40]
How issue was created:
Modrinth Fabric 1.19.4
	- ecu 1.3.0
	- essential-container 1.0.0
	   \-- essential-loader 1.2.1
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- java 17
	- minecraft 1.19.4

What happened:
Opened wardrobe, all/most cosmetics still cost coins to unlock.
Game did not crash
ran game x2
Error logs related to essentials and ecu:
[main/WARN]:
 Error loading class: gg/essential/network/connectionmanager/cosmetics/CosmeticsManager (java.lang.ClassNotFoundException: gg/essential/network/connectionmanager/cosmetics/CosmeticsManager)
[main/WARN]:
 @Mixin target gg.essential.network.connectionmanager.cosmetics.CosmeticsManager was not found mixins.ecu.json:other.essential.cosmetics.MixinCosmeticsManager from mod ecu
[main/WARN]:
 Error loading class: gg/essential/network/connectionmanager/handler/cosmetics/ServerCosmeticsPopulatePacketHandler (java.lang.ClassNotFoundException: gg/essential/network/connectionmanager/handler/cosmetics/ServerCosmeticsPopulatePacketHandler)
[main/WARN]:
 @Mixin target gg.essential.network.connectionmanager.handler.cosmetics.ServerCosmeticsPopulatePacketHandler was not found mixins.ecu.json:other.essential.cosmetics.MixinServerCosmeticsPopulatePacketHandler from mod ecu

**Comment by wildcodemaster** [comment]
Tried running it with legacy instead:
[error.txt](https://github.com/dxxxxy/EssentialCosmeticsUnlocker/files/15359624/error.txt)

**Comment by dxxxxy** [comment]
You most likely do not have the right Essential mod.
