### ISSUE TITLE
Wont work on 1.20.1

### ISSUE THREAD

**Issue by Strealstud** [dxxxxy/EssentialCosmeticsUnlocker#48]
It wont work on 1.20.1  i have 1.3.2.4 essential

**Comment by cootshk** [comment]
Fabric or forge?

**Comment by Strealstud** [comment]
Fabric

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by letruxux** [comment]
ive tried 1.20.1 fabric and its working just fine

**Comment by Strealstud** [comment]
Ok that’s weird must be a mod compatibility issue

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
