### ISSUE TITLE
1.21 support?

### ISSUE THREAD

**Issue by BebroNUXXX** [dxxxxy/EssentialCosmeticsUnlocker#50]

**Comment by dxxxxy** [comment]
Could you try to see if it works? Technically, this project should support all versions unless major changes to the mod loader are introduced.

**Comment by KITOXIS** [comment]
I just tested it, it works on 1.21!

**Comment by mihailik02** [comment]
![Снимок экрана 2024-06-30 102015](https://github.com/dxxxxy/EssentialCosmeticsUnlocker/assets/49747238/f75e3eb9-3e3a-4cad-b2d6-16a6b73fe786)
![Снимок экрана 2024-06-30 102107](https://github.com/dxxxxy/EssentialCosmeticsUnlocker/assets/49747238/e2db760a-9e1e-4e67-adb9-5f1bd63661c8)
Мод работает на 1.21 ткань
Только долго не мог понять как установить
добавьте более подробную инструкцию по установке, спасибо за вашу работу

**Comment by nerch11** [comment]
@mihailik02 не мог ли бы ты мне помочь установить этот мод на версию 1.21?

**Comment by mihailik02** [comment]
@nerch11 по сути всё просто, сначала надо установить сам мод essential и запустить игру, после этого в папке с игной появится папка essential.
из папки mods надо удалить мод, и скопировать из папки essential файл "Essential (fabric_1.20.6).jar" в папку mods
и "ecu-1.4.0.jar" также закинуть в папку mods

**Comment by nerch11** [comment]
@mihailik02 спасибо тебе большое, а то мне тут даже было сложно просто мод скачать

**Comment by BebroNUXXX** [comment]
@mihailik02 просто герой, спасибо

**Comment by BebroNUXXX** [comment]
@mihailik02 не робит, просто краши постоянные. На полной ваниле тестил?

**Comment by mihailik02** [comment]
@BebroNUXXX ну по сути чистый фабрик, только после этих тестов уже ставил моды и всё работает

**Comment by BebroNUXXX** [comment]
@mihailik02 это пиздец. Я перебрал сборку на 200+ модов полностью
оно с ВИА ФАБРИК **ПЛЮС** КОНФЛИКТУЕТ
а самое смешное что с обычным виа фабриком все ок

**Comment by Eternal272** [comment]
how do you install this
