### ISSUE TITLE
İs this virus?

### ISSUE THREAD

**Issue by Batuking1111** [dxxxxy/EssentialCosmeticsUnlocker#6]
https://www.virustotal.com/gui/file/4693a6fa1528181e51f4317efa452d2dbafad075e8dc13ff8588c32a37e945d8/detection

**Comment by Batuking1111** [comment]
I'm not sure it's a virus, but 3 antivirus programs give warnings.

**Comment by dxxxxy** [comment]
It's open source. If you are worried then build it yourself instead of asking questions.

**Comment by Batuking1111** [comment]
ok

**Comment by nathanfranke** [comment]
The uploaded release jar could always be different from the source code.

However, I decompiled `ecu-1.3.0-legacy.jar` with https://www.decompiler.com/ and went through each file.

### There is nothing suspicious. The code is concise enough for anyone to go through.

My convoluted approach:

- There is nothing suspicious in the 3 java files in `studio.dreamys.ecu.mixin`.

- I decompiled the shaded library from here: https://repo.spongepowered.org/repository/maven-public/org/spongepowered/mixin/0.7.10-SNAPSHOT/mixin-0.7.10-20180616.121809-3.jar
- I compared the decompiled java files in each `org/spongepowered` directory with `find . -type f -exec sha256sum {} \;`. **They are exactly the same.**
- The raw class files in `org/spongepowered` are different. This might be a normal function of shading dependencies.
- I find it very unlikely a virus would be hidden in a java class file, but not visible in the decompiled source code.

- There is nothing suspicious any of the other files in the jar (6 files + META-INF).
