### ISSUE TITLE
Crashing caused by uploading skin?

### ISSUE THREAD

**Issue by MaximusXgamer** [dxxxxy/EssentialCosmeticsUnlocker#63]
Uploading skin when Essential mod from the essential folder is put into the mods folder instantly crashes the game.

[The crash report received when trying to upload a skin.](https://github.com/user-attachments/files/16841538/hs_err_pid24104.log)

[Edited to also include the latest log. The Essential Bot told me to remove the Essential mod from the mods folder, but if I do then ECU won't work.](https://github.com/user-attachments/files/16841560/latest.log)

**Comment by dxxxxy** [comment]
I do not know what you mean by uploading a skin. We do not offer support for issues related to Essential's own features.
