### ISSUE TITLE
Cosmetics not showing in multiplayer.

### ISSUE THREAD

**Issue by MisplacedFlowerpot** [dxxxxy/EssentialCosmeticsUnlocker#64]
as stated in the title when you the cosmetics unlocked this way in a multiplayer server others can't see the cosmetics. I'm working with the newest version on 1.19.2.

**Comment by dxxxxy** [comment]
This is the intended behaviour.

**Comment by MisplacedFlowerpot** [comment]
why if i may ask?

**Comment by dxxxxy** [comment]
That is the limit of what a client-side patch can do, as stated in the README.

**Comment by MisplacedFlowerpot** [comment]
alright, thanks for the help. guess i missed that part when reading the README.
