### ISSUE TITLE
Don't Think It Still Works

### ISSUE THREAD

**Issue by CazymirTM** [dxxxxy/EssentialCosmeticsUnlocker#7]
So i put the new one 1.2.1 in the mods folder (im playing on 1.20.1 mc version), with fabric, but in game it doesn't unlock anything, any idea?

**Comment by dxxxxy** [comment]
Post your mods folder.

**Comment by CazymirTM** [comment]
![Screenshot_1](https://github.com/dxxxxy/EssentialCosmeticsUnlocker/assets/91396680/45b80ce9-7add-48a7-a0db-27cffb0cf734)

**Comment by dxxxxy** [comment]
> ![Screenshot_1](https://github.com/dxxxxy/EssentialCosmeticsUnlocker/assets/91396680/45b80ce9-7add-48a7-a0db-27cffb0cf734)
> 
> 

You do not have the right Essential mod. See notes about Fabric in the README's Compatibility section.

**Comment by CazymirTM** [comment]
> > ![Screenshot_1](https://user-images.githubusercontent.com/91396680/264687451-45b80ce9-7add-48a7-a0db-27cffb0cf734.png)
> 
> You do not have the right Essential mod. See notes about Fabric in the README's Compatibility section.

I just put the essential 1.20 (as you said in compatibility), still doesn't work

**Comment by dxxxxy** [comment]
Read again. You have the wrong Essential mod.

**Comment by CazymirTM** [comment]
> Read again. You have the wrong Essential mod.

Wait but what essential do i need to download?
Im sorry im confused.

**Comment by CazymirTM** [comment]
> > > Read again. You have the wrong Essential mod.
> > 
> > 
> > Wait but what essential do i need to download?
> > Im sorry im confused.
> 
> You do not need to download anything else. Read it again.

Do you mean to get the legacy version for fabric or?

**Comment by dxxxxy** [comment]
> > > > Read again. You have the wrong Essential mod.
> 
> > > 
> 
> > > 
> 
> > > Wait but what essential do i need to download?
> 
> > > Im sorry im confused.
> 
> > 
> 
> > You do not need to download anything else. Read it again.
> 
> 
> 
> Do you mean to get the legacy version for fabric or?

What are you even reading?

**Comment by dxxxxy** [comment]
> > ![Screenshot_1](https://github.com/dxxxxy/EssentialCosmeticsUnlocker/assets/91396680/45b80ce9-7add-48a7-a0db-27cffb0cf734)
> > 
> > 
> 
> You do not have the right Essential mod. See notes about Fabric in the README's Compatibility section.

Did you ignore this message?

**Comment by CazymirTM** [comment]
> > > ![Screenshot_1](https://user-images.githubusercontent.com/91396680/264687451-45b80ce9-7add-48a7-a0db-27cffb0cf734.png)
> > 
> > 
> > You do not have the right Essential mod. See notes about Fabric in the README's Compatibility section.
> 
> Did you ignore this message?

No, but i don't understand

**Comment by dxxxxy** [comment]
Paste what you read.

**Comment by BlueFalconHD** [comment]
> Paste what you read.

LMAOO getting some people to understand stuff is a literal shitshow

**Comment by dxxxxy** [comment]
> > Paste what you read.
> 
> LMAOO getting some people to understand stuff is a literal shitshow

😭
