### ISSUE TITLE
why when I put your Essential unlocked, my minecraft does not enter?

### ISSUE THREAD

**Issue by Pandoka278** [dxxxxy/EssentialCosmeticsUnlocker#8]

**Comment by dxxxxy** [comment]
I don't know, what did you do?

**Comment by Pandoka278** [comment]
well...i want to get the legacy ecu for 1.18.2 and it says i need the 6/12/23 ecu version but when i look at the releases only the 7/9/23 version is available...

**Comment by Pandoka278** [comment]
actually it seems to be a problem with the mod itself, not the version... but anyway, i already tested ecu version 1.2.1 and 1.2.0

**Comment by dxxxxy** [comment]
> well...i want to get the legacy ecu for 1.18.2 and it says i need the 6/12/23 ecu version but when i look at the releases only the 7/9/23 version is available...

`ecu-legacy` is a compatibility fix for older versions of Minecraft (< 1.12). This is why both are present in the same release (for universal compatibility). If you are using Forge, simply drop the mod without the `legacy` classifier and you're good to go. If you are using Fabric, there are some extra steps that are explained in the Notes section of the README, however, you still use the non-legacy variant of the mod.

**Comment by Pandoka278** [comment]
ok i will use normal 1.2.1 ecu

**Comment by dxxxxy** [comment]
Closed due to inactivity.
