### ISSUE TITLE
Mod out of date?

### ISSUE THREAD

**Issue by AwertaDreams** [dxxxxy/EssentialCosmeticsUnlocker#9]
Heya! installed ur mod, im using fabric 1.20.1. But there's a slight problem - it crashes upon launching minecraft.

**Comment by VilotStar** [comment]
I'm not having any issues, are you sure you have the 48 MB essential jar (Essential (fabric_1.20.1).jar) in the mods (.minecraft/mods) folder, and you should have the unlocker jar (ecu-1.2.1.jar) in the the same folder (.minecraft/mods)

**Comment by dxxxxy** [comment]
Closed due to inactivity.
